### PR TITLE
finished clone

### PR DESCRIPTION
**Pull request by jabichris**
#### What does this PR do?

- It brings in the full content of the youtube cloned page

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under review by Oluwadamilare Olusakin(TSE) :rocket:

**Comment by nikasulo** [comment]
# You've done a fantastic job so far @jabichris, for one, your markup is semantically correct!
There are however a few changes that you need to make before you can go on to merge this, and that being said, I will list a few:

#### Design 
* The search bar needs to be a <button> as stipulated by the Microverse requirements
screenshot
* The page currently allows, horizontal scrolling which it shouldn't, please look into it and fix this.
* Your navigation could be a little tidier and this will help your project shine! Please look closely at the original Youtube navigation and compare the spacing between icons, as well as the padding on the top and the sides of the navbar as well.
* We could also put in a bit more work on the aside section with the video recommendations, I know CSS can be a little frustrating at times, however, one thing that has really helped me is understanding the flexbox property. Please read this [article](https://www.w3schools.com/css/css3_flexbox.asp) as well as this [article](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) you will find it helpful! They helped me a great deal :smile:.
* The pictures currently in the recommended videos section should be video thumbnails, not photographs, please consider this as it is a requirement.
*  Lastly, consider comparing the sizing of the various elements on the page as they have say in how your websites are percieved, your elements are a little on the large side, try reducing the and see if you can notice how it feels on your eyes as opposed to their current size.

# Summary :rocket:  
You've done such a great job! Your markup is exquisite, just look into some of the things I have listed above and submit for a re-review! :handshake:

If you need any assistance, help or you just want to talk, please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_), [Instagram](https://instagram.com/oluwadamilareolusakin) or [Linkedin](https://www.linkedin.com/in/oluwadamilare-olusakin-99a1b584) and I will be sure to help however I can

**Comment by nikasulo** [comment]
# Great work! :rocket: 
Really nice job implementing the Readme file and adding the button to the navbar, however the styling still needs a bit of work.

#### Navbar
* Please look at each element in the navbar one at a time and compare them with the elements on the original page's navigation. Look out for sizing, spacing between elements, etc. These things really do matter.

#### Horizontal scrolling
* Look into the bug causing your page to scroll horizontally, see the screenshots I've attached below, likely you have a margin or padding setup on some element that is causing all the commotion.

#### Recommended videos section
* Your recommended videos section can use a bit more work, for one, you still have pictures going on there instead of videos.
* One of the effects you have on there is causing a bit of horizontal scrolling. 
* Look into the spacing of the elements in this sections, compare closely with those of the original page and adjust accordingly :smile:.

# Summary
You have a great thing going! A lot of these projects are really great because they give you a chance to see how industry leaders build their sites. Attention to detail is very key as it directly affects user experience. Give it some thought and extra looks, you have a great example (the original site), follow closely! :smile: :+1:.

**Review by suretrust — APPROVED** [review]
Hi @jabichris @Genius8,

### Amazing job guys! :raised_hands:  Let's get this merged! :+1: 

_Good luck with your future projects and happy coding_ :tada:

**Pull request merged**
